version: '3'
services:
  # MySQL service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: assurance
      MYSQL_PASSWORD: admin

  # Eureka server
  discovery-service:
    image: eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
  # Spring Boot application service
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - eureka-server
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/assurance
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  API-GATEWAY-SERVICE:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - spring-app


